{"author":{"id":"e970470018827b6b178556f877e6452433eeadb8d713d3499b58f62b3765b664"},"ops":[{"type":3,"author":{"id":"e970470018827b6b178556f877e6452433eeadb8d713d3499b58f62b3765b664"},"timestamp":1694689094,"metadata":{"github-id":"IC_kwDODbKJfs5meWGV","github-url":"https://github.com/vmiklos/plees-tracker/issues/406#issuecomment-1719230869"},"nonce":"KLAbCN9ipEDNBpliUxFIr4SRPCk=","message":"Follow-up: there still is a problem, when a file already exists: https://github.com/vmiklos/plees-tracker/issues/414","files":null},{"type":6,"author":{"id":"e970470018827b6b178556f877e6452433eeadb8d713d3499b58f62b3765b664"},"timestamp":1694689136,"metadata":{"github-id":"UCE_lALODbKJfs5meWGVzjde5dk"},"nonce":"0ZOuOU1oZ9c/s5CbmwJ9R9Gb7Ps=","target":"4a0e009736391159c3b0d60a86b44d6380e37659b57262d1e8ebe11d70edb208","message":"Follow-up: there still is a problem, when a file already exists: https://github.com/vmiklos/plees-tracker/issues/414\nOtherwise export to Nextcloud works fine now.","files":null}]}